# Generated by Django 6.0.1 on 2026-01-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_entries",
                to="parts.part",
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="storages", to="core.attachment"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="storage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_in_location",
                to="inventory.storage",
            ),
        ),
    ]
