# Generated by Django 6.0.1 on 2026-01-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_lot_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name_plural": "Stock"},
        ),
        migrations.AlterModelOptions(
            name="storage",
            options={"verbose_name_plural": "Storage"},
        ),
    ]
