# Generated by Django 6.0.1 on 2026-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_company_options"),
        ("inventory", "0004_alter_stock_options_alter_storage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="lots", to="core.attachment"
            ),
        ),
    ]
