# Generated by Django 6.0.1 on 2026-01-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_lot_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.storage'),
        ),
    ]
