# Generated by Django 6.0.1 on 2026-01-19 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_alter_part_substitutes"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="revision",
            field=models.CharField(default="1.0", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "designators",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated designators (e.g. R1, R2)",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_usage",
                        to="parts.part",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_items",
                        to="projects.project",
                    ),
                ),
                (
                    "substitutes",
                    models.ManyToManyField(
                        blank=True, related_name="bom_substitutes", to="parts.part"
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Item",
                "verbose_name_plural": "BOM Items",
                "abstract": False,
            },
        ),
    ]
