# Generated by Django 6.0.1 on 2026-01-19 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("datasheet", "Datasheet"),
                            ("cad", "CAD File"),
                            ("gerbers", "Gerbers"),
                            ("kicad-pcb", "KiCad PCB"),
                            ("eagle-brd", "Eagle Board"),
                            ("invoice", "Invoice"),
                            ("purchase-order", "Purchase Order"),
                            ("shipping-list", "Shipping List"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.IntegerField(default=0)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("is_manufacturer", models.BooleanField(default=False)),
                ("is_vendor", models.BooleanField(default=False)),
                ("contacts", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
