# Generated by Django 6.0.1 on 2026-01-19 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "part_type",
                    models.CharField(
                        choices=[
                            ("sub-assembly", "Sub-Assembly"),
                            ("meta", "Meta-Part"),
                            ("linked", "Linked Part"),
                            ("local", "Local Part"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True, help_text="Markdown supported")),
                ("footprint", models.CharField(blank=True, max_length=255)),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Manufacturer Part Number",
                    ),
                ),
                ("cad_keys", models.JSONField(blank=True, default=list)),
                ("low_stock_threshold", models.IntegerField(blank=True, null=True)),
                ("attrition_percent", models.FloatField(default=0.0)),
                ("attrition_quantity", models.IntegerField(default=0)),
                ("is_default_storage_mandatory", models.BooleanField(default=False)),
                ("project_id_ref", models.UUIDField(blank=True, null=True)),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, related_name="parts", to="core.attachment"
                    ),
                ),
                (
                    "default_storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_parts",
                        to="inventory.storage",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_manufacturer": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufactured_parts",
                        to="core.company",
                    ),
                ),
                (
                    "meta_parts",
                    models.ManyToManyField(
                        blank=True, related_name="meta_parents", to="parts.part"
                    ),
                ),
                (
                    "substitutes",
                    models.ManyToManyField(
                        blank=True, related_name="substituted_by", to="parts.part"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
