# Generated by Django 6.0.1 on 2026-01-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_remove_part_project_id_ref"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="part_assemblies",
                to="projects.project",
            ),
        ),
    ]
