# Generated by Django 6.0.1 on 2026-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_part_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="substitutes",
            field=models.ManyToManyField(blank=True, to="parts.part"),
        ),
    ]
