# Generated by Django 6.0.1 on 2026-01-20 04:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_alter_part_substitutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Designator",
                "verbose_name_plural": "Designators",
                "abstract": False,
            },
        ),
    ]
