# Generated by Django 6.0.1 on 2026-01-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0005_designator"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="designator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts",
                to="parts.designator",
            ),
        ),
    ]
