# Generated by Django 6.0.1 on 2026-01-19 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("parts", "0002_remove_part_project_id_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("online", "Online"),
                            ("service", "Service"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, help_text="Vendor SKU", max_length=255
                    ),
                ),
                (
                    "moq",
                    models.IntegerField(
                        default=1, verbose_name="Minimum Order Quantity"
                    ),
                ),
                ("order_multiple", models.IntegerField(default=1)),
                ("prices", models.JSONField(blank=True, default=list)),
                (
                    "in_stock_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("maybe", "Maybe"),
                            ("assumed", "Assumed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, related_name="offers", to="core.attachment"
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="parts.part",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_vendor": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "number",
                    models.CharField(help_text="Vendor Order Number", max_length=255),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=255)),
                (
                    "po_number",
                    models.CharField(
                        blank=True, help_text="Internal PO Number", max_length=255
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("expected_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        limit_choices_to={"is_vendor": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
