# Generated by Django 6.0.1 on 2026-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_company_options"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="core.attachment"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("ordered", "Ordered"),
                    ("received", "Received"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
